server:
  port: 8002
spring:
  application:
    name: spring-cloud-registerApp
#  rabbitmq:
#    username:
#    password:
#    port: 5672
#    host:
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true
